version: "3.1"

services:
  db:
    container_name: moviesDB
    image: mongo:latest
    restart: always
    volumes:
      - ./moviesData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Movies
    ports:
      - 27017:27017